### ISSUE TITLE
The results were very different from GRCH37 and GRCH38.

### ISSUE THREAD

**Issue by renyuan001** [icbi-lab/NeoFuse#22]
I use 10 samples and analysed both by GRCH37 and GRCH38. I conpared the ***filtered.tsv and unfiltered.tsv between GRCH37 and GRCH38. The fusion genes and locations were all different.  No same result were found and it seems like the result referenced by GRCH38 was much fewer than the result referenced by GRCH37. Please tell me the reason， thank you! 
$ NeoFuse -R -o GRCH37 -n 20 -V GRCH37 --docker
$ NeoFuse -R -o GRCH38 -n 20 -V GRCH38 --docker
These orders were used to generate reference.

**Comment by abyssum** [comment]
Hello @renyuan001,

First of all, thank you for using NeoFuse.

To briefly answer your question, since GRCh38 (hg38) is and update of GRCh37 (hg19), there are several thousand individual bases updated in GRCh38, many of which corrected errors in coding sequences. Since this is beyond the scope of NeoFuse, I will not elaborate on the differences between the two versions (there is plenty of information available, this [publication](https://www.sciencedirect.com/science/article/pii/S0888754317300058) for example).

Although, I haven't  tried to compare the results from the two versions myself, I would expect that you would find major differences between GRCh37 and GRCh38 as you mentioned (especially when it comes to genomic positions). As a quick example, consider BRCA2:
- According to GRCh37 the genomic coords of the coding positions for BRCA2 are as follows: [chr13:32,890,598-32,972,907](https://genome.ucsc.edu/cgi-bin/hgGene?db=hg19&hgg_gene=BRCA2)
- According to GRCh38 the genomic coords of the coding positions for BRCA2 are as follows: [chr13:32,315,086-32,400,268](https://www.ensembl.org/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32315086-32400268)

Following the previous example, let's say that the majority of the sequenced reads of your sample fall under the genomic position **chr13: 32,315,086-32,400,268**. Then depending on the annotation you would be using, BRCA2 may be called (using GRCh38) or not (when using GRCh37).

Given the fact that in order for Arriba to call a fusion the reads should span the junction point (for more info please read the [arriba documentation](https://arriba.readthedocs.io/en/latest/output-files/) regarding split reads, discordant mates and coverage), it is expected that since GRCh38 is more robust it will - probably - yield less results (meaning that GRCh37 might yield more results which are potentially false positives).

I hope this helps.

**Comment by renyuan001** [comment]
Thank you for your kind reply and I will use GRCh38 to analysis my samples. It is a good tool for screening neoantigen from genefusion.

**Comment by abyssum** [comment]
I am glad I could help.

Once again thank you for supporting NeoFuse and please let me know if you encounter any issues.

As a side note, we will be updating NeoFuse to a newer version in the following months.
Some of the new features include:
- [NextFlow DSL2](https://www.nextflow.io/blog/2020/dsl2-is-here.html) infrastructure according to the [nf-core](https://nf-co.re/) guidelines.
-  Support for MHC class II neoantigens.
- Neoantigen prioritization scheme according to [pvacfuse](https://pvactools.readthedocs.io/en/latest/pvacfuse.html).

You can "watch" the current repo version to get notification for future updates.
